version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: "[CI] "
    target-branch: "develop"
    labels:
      - "bot"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]