site_name: Cedict dictionary - Documentation
repo_url: https://github.com/Tykok/cedict-chinese-transformation
theme: 
    name: readthedocs
    locale: en
    highlightjs: true
    hljs_style: github
    hljs_languages:
        - javascript
        - typescript
        - bash
nav:
    - Home: index.md
    - Cedict: cedict.md
    - Cedict-Cli: cedict-cli.md