name: Auto approve
on: pull_request_target

jobs:
  autoapprove:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v3
      if: github.actor == 'dependabot[bot]'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"