name: Auto approve 🤖
on:
  pull_request_target:
    paths:
      - "package.json"

jobs:
  autoapprove:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"