name: Auto merge 🤖
on:
  pull_request_target:
    paths:
      - "package.json"
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled
      - ready_for_review
permissions:
  pull-requests: write
  contents: write
  
jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
    - name: Enable Pull Request Automerge
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        token: ${{ secrets.PAT }}
        pull-request-number: ${{ github.event.number }}
        merge-method: rebase