name: Latest blog post workflow
on:
  schedule:
    - cron: '00 6 15 * *' 
  workflow_dispatch:

jobs:
  update-cedict:
    name: Update the JSON cedict file used in the library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Run scripts to get cedict
        run: npm run get-cedict
      - name: Update cedict.json
        run: |
          git config --global user.name 'CI'
          git config --global user.email 'ci.cron@github.com'
          git add lib/cedict.json
          git commit -m "Update cedict.json"
          git push