name: Unpublish version

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version to unpublish
        required: true

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Unpublish package on npmjs.com
        run: npm unpublish @tykok/cedict-dictionary@${{input.version}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}